LANGUAGES = {
    'English': {
        'app_title': 'Warehouse Management System',
        'products_tab': 'Products',
        'categories_tab': 'Categories',
        'suppliers_tab': 'Suppliers',
        'inventory_tab': 'Inventory',
        'product_details': 'Product Details',
        'category_details': 'Category Details',
        'supplier_details': 'Supplier Details',
        'inventory_details': 'Inventory Details',
        'name': 'Name',
        'description': 'Description',
        'price': 'Price',
        'category': 'Category',
        'supplier': 'Supplier',
        'contact_name': 'Contact Name',
        'phone': 'Phone',
        'email': 'Email',
        'product': 'Product',
        'quantity': 'Quantity',
        'last_updated': 'Last Updated',
        'id': 'ID',
        'language': 'Language',
        'add': 'Add',
        'update': 'Update',
        'delete': 'Delete',
        'clear': 'Clear Fields',
        'confirm_delete': 'Are you sure you want to delete this {}?',
        'product_name_required': 'Product name is required!',
        'price_must_be_greater_than_zero': 'Price must be greater than 0!',
        'invalid_price_format': 'Invalid price format!',
        'please_select_a_product_to_update': 'Please select a product to update!',
        'please_select_a_product_to_delete': 'Please select a product to delete!',
        'product_added_successfully': 'Product added successfully!',
        'product_updated_successfully': 'Product updated successfully!',
        'product_deleted_successfully': 'Product deleted successfully!',
        'category_name_required': 'Category name is required!',
        'please_select_a_category_to_update': 'Please select a category to update!',
        'please_select_a_category_to_delete': 'Please select a category to delete!',
        'category_added_successfully': 'Category added successfully!',
        'category_updated_successfully': 'Category updated successfully!',
        'category_deleted_successfully': 'Category deleted successfully!',
        'supplier_name_required': 'Supplier name is required!',
        'please_select_a_supplier_to_update': 'Please select a supplier to update!',
        'please_select_a_supplier_to_delete': 'Please select a supplier to delete!',
        'supplier_added_successfully': 'Supplier added successfully!',
        'supplier_updated_successfully': 'Supplier updated successfully!',
        'supplier_deleted_successfully': 'Supplier deleted successfully!',
        'please_select_a_product': 'Please select a product!',
        'quantity_cannot_be_negative': 'Quantity cannot be negative!',
        'invalid_quantity_format': 'Invalid quantity format!',
        'invalid_product_selected': 'Invalid product selected!',
        'inventory_updated_successfully': 'Inventory updated successfully!',
        'inventory': 'Inventory',
        'product': 'Product',
        'category': 'Category',
        'supplier': 'Supplier'
    },
    'Vietnamese': {
        'app_title': 'Hệ Thống Quản Lý Kho',
        'products_tab': 'Sản Phẩm',
        'categories_tab': 'Danh Mục',
        'suppliers_tab': 'Nhà Cung Cấp',
        'inventory_tab': 'Tồn Kho',
        'product_details': 'Chi Tiết Sản Phẩm',
        'category_details': 'Chi Tiết Danh Mục',
        'supplier_details': 'Chi Tiết Nhà Cung Cấp',
        'inventory_details': 'Chi Tiết Tồn Kho',
        'name': 'Tên',
        'description': 'Mô Tả',
        'price': 'Giá',
        'category': 'Danh Mục',
        'supplier': 'Nhà Cung Cấp',
        'contact_name': 'Tên Liên Hệ',
        'phone': 'Điện Thoại',
        'email': 'Email',
        'product': 'Sản Phẩm',
        'quantity': 'Số Lượng',
        'last_updated': 'Cập Nhật Lần Cuối',
        'id': 'ID',
        'language': 'Ngôn Ngữ',
        'add': 'Thêm',
        'update': 'Cập Nhật',
        'delete': 'Xóa',
        'clear': 'Xóa Trường',
        'confirm_delete': 'Bạn có chắc chắn muốn xóa {} này không?',
        'product_name_required': 'Tên sản phẩm là bắt buộc!',
        'price_must_be_greater_than_zero': 'Giá phải lớn hơn 0!',
        'invalid_price_format': 'Định dạng giá không hợp lệ!',
        'please_select_a_product_to_update': 'Vui lòng chọn sản phẩm để cập nhật!',
        'please_select_a_product_to_delete': 'Vui lòng chọn sản phẩm để xóa!',
        'product_added_successfully': 'Thêm sản phẩm thành công!',
        'product_updated_successfully': 'Cập nhật sản phẩm thành công!',
        'product_deleted_successfully': 'Xóa sản phẩm thành công!',
        'category_name_required': 'Tên danh mục là bắt buộc!',
        'please_select_a_category_to_update': 'Vui lòng chọn danh mục để cập nhật!',
        'please_select_a_category_to_delete': 'Vui lòng chọn danh mục để xóa!',
        'category_added_successfully': 'Thêm danh mục thành công!',
        'category_updated_successfully': 'Cập nhật danh mục thành công!',
        'category_deleted_successfully': 'Xóa danh mục thành công!',
        'supplier_name_required': 'Tên nhà cung cấp là bắt buộc!',
        'please_select_a_supplier_to_update': 'Vui lòng chọn nhà cung cấp để cập nhật!',
        'please_select_a_supplier_to_delete': 'Vui lòng chọn nhà cung cấp để xóa!',
        'supplier_added_successfully': 'Thêm nhà cung cấp thành công!',
        'supplier_updated_successfully': 'Cập nhật nhà cung cấp thành công!',
        'supplier_deleted_successfully': 'Xóa nhà cung cấp thành công!',
        'please_select_a_product': 'Vui lòng chọn sản phẩm!',
        'quantity_cannot_be_negative': 'Số lượng không thể âm!',
        'invalid_quantity_format': 'Định dạng số lượng không hợp lệ!',
        'invalid_product_selected': 'Sản phẩm đã chọn không hợp lệ!',
        'inventory_updated_successfully': 'Cập nhật tồn kho thành công!',
        'inventory': 'tồn kho',
        'product': 'Sản phẩm',
        'category': 'Danh mục',
        'supplier': 'Nhà cung cấp'
    }
}
