CREATE TABLE IF NOT EXISTS PHANQUYEN (
    ma_quyen INT PRIMARY KEY AUTO_INCREMENT,
    ten_quyen VARCHAR(50) NOT NULL UNIQUE,
    mo_ta TEXT
);

INSERT INTO PHANQUYEN (ten_quyen, mo_ta) VALUES
('administrator', 'Quyền truy cập đầy đủ vào tất cả tính năng'),
('registered_user', 'Chờ phê duyệt'),
('user', 'Chỉ xem'),
('manager', 'Quyền quản lý tất cả trừ người dùng'); 

CREATE TABLE IF NOT EXISTS NGUOIDUNG (
    ma_nguoi_dung INT PRIMARY KEY AUTO_INCREMENT,
    ten_dang_nhap VARCHAR(50) NOT NULL UNIQUE,
    mat_khau VARCHAR(255) NOT NULL,
    ho_ten VARCHAR(255) NOT NULL,
    ma_quyen INT NOT NULL,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ma_quyen) REFERENCES PHANQUYEN(ma_quyen)
);

CREATE TABLE IF NOT EXISTS DANHMUC (
    ma_danh_muc INT PRIMARY KEY AUTO_INCREMENT,
    ten VARCHAR(100) NOT NULL UNIQUE,
    mo_ta TEXT,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS NHACUNGCAP (
    ma_ncc INT PRIMARY KEY AUTO_INCREMENT,
    ten VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    dien_thoai VARCHAR(20),
    dia_chi TEXT,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SANPHAM (
    ma_san_pham INT PRIMARY KEY AUTO_INCREMENT,
    ten VARCHAR(100) NOT NULL,
    mo_ta TEXT,
    ma_danh_muc INT,
    ma_ncc INT,
    don_gia DECIMAL(10, 2) NOT NULL,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ma_danh_muc) REFERENCES DANHMUC(ma_danh_muc),
    FOREIGN KEY (ma_ncc) REFERENCES NHACUNGCAP(ma_ncc)
);

CREATE TABLE IF NOT EXISTS KHOHANG (
    ma_kho INT PRIMARY KEY AUTO_INCREMENT,
    ma_san_pham INT NOT NULL,
    so_luong INT NOT NULL DEFAULT 0,
    ngay_nhap_cuoi TIMESTAMP,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ma_san_pham) REFERENCES SANPHAM(ma_san_pham)
);

CREATE TABLE IF NOT EXISTS DONHANG (
    ma_don_hang INT PRIMARY KEY AUTO_INCREMENT,
    ma_nguoi_dung INT NOT NULL,
    ngay_dat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tong_tien DECIMAL(10, 2) NOT NULL,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ma_nguoi_dung) REFERENCES NGUOIDUNG(ma_nguoi_dung)
);

CREATE TABLE IF NOT EXISTS CHITIETDONHANG (
    ma_chi_tiet INT PRIMARY KEY AUTO_INCREMENT,
    ma_don_hang INT NOT NULL,
    ma_san_pham INT NOT NULL,
    so_luong INT NOT NULL,
    don_gia DECIMAL(10, 2) NOT NULL,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ma_don_hang) REFERENCES DONHANG(ma_don_hang),
    FOREIGN KEY (ma_san_pham) REFERENCES SANPHAM(ma_san_pham)
);
